academico/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from home import urls as home_urls
from student import urls as student_urls
from teachers import urls as teachers_urls
from syllabus import urls as syllabus_urls
from enrollment import urls as enrollment_urls
from ratings import urls as ratings_urls
from attendance import urls as attendance_urls

urlpatterns = [
    url(r'^', include(home_urls, namespace='home')),
    url(r'^estudiantes/', include(student_urls, namespace='student')),
    url(r'^profesores/', include(teachers_urls, namespace='teacher')),
    url(r'^pensum/', include(syllabus_urls, namespace='syllabus')),
    url(r'^matriculas/', include(enrollment_urls, namespace='enrollment')),
    url(r'^calificaciones/', include(ratings_urls, namespace='ratings')),
    url(r'^asistencia/', include(attendance_urls, namespace='attendance')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from .views import HomeView, LogoutView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

teachers/urls.py
from django.conf.urls import url

from .views import ListTeachersView, AddTeacherView, DetailTeacherView, EditTeacherView

urlpatterns = [
    url(r'^$', ListTeachersView.as_view(), name='list'),
    url(r'^agregar/$', AddTeacherView.as_view(), name='add'),
    url(r'^detalle/(?P<pk>\d+)/$', DetailTeacherView.as_view(), name='detail'),
    url(r'^editar/(?P<pk>\d+)/$', EditTeacherView.as_view(), name='edit'),
]

teachers/models.py
from django.contrib.auth.models import User
from django.db import models

from helpers import dictionaries
from home.models import TimeStampUser


class Teacher(TimeStampUser):
    user = models.OneToOneField(
        User,
        verbose_name='Usuario'
    )

    document_type = models.CharField(
        verbose_name='Tipo de documento',
        max_length=2,
        choices=dictionaries.DOCUMENT_TYPE,
        default='CC'
    )

    document_number = models.BigIntegerField(
        verbose_name='Número de documento'
    )

    address = models.CharField(
        verbose_name='Dirección',
        max_length=250,
    )

    phone = models.BigIntegerField(
        verbose_name='Teléfono'
    )

    cellphone = models.BigIntegerField(
        verbose_name='Celular'
    )

    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    def get_full_name(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


# class AssignTeacher(TimeStampUser):
#     teacher = models.ForeignKey(
#         Teacher,
#         verbose_name='Profesor'
#     )
#     matter = models.ForeignKey(
#         Syllabus,
#         verbose_name='Materia'
#     )
#
#     class Meta:
#         verbose_name = 'Asignación de profesores'
#         verbose_name_plural = 'Asignación de profesores'
#         default_permissions = ('add', 'change', 'delete', 'view',)
#
#     def __str__(self):
#         return '{} - {} - {}'.format(self.teacher.get_full_name(), self.matter.name_matter)

teachers/forms.py
from django import forms
from .models import Teacher


class TeacherForm(forms.ModelForm):

    username = forms.CharField(
        label='Nombre de usuario'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Contraseña',
    )
    first_name = forms.CharField(
        label='Nombres'
    )
    last_name = forms.CharField(
        label='Apellidos'
    )
    email = forms.EmailField(
        label='Correo electrónico'
    )

    class Meta:
        model = Teacher
        exclude = ('user', 'created_by', 'updated_by',)
        widgets = {
            'document_number': forms.TextInput(),
            'phone': forms.TextInput(),
            'cellphone': forms.TextInput()
        }


class TeacherEditForm(forms.ModelForm):

    username = forms.CharField(
        label='Nombre de usuario'
    )
    first_name = forms.CharField(
        label='Nombres'
    )
    last_name = forms.CharField(
        label='Apellidos'
    )
    email = forms.EmailField(
        label='Correo electrónico'
    )

    class Meta:
        model = Teacher
        exclude = ('user', 'created_by', 'updated_by',)

teachers/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from .models import Teacher
from .forms import TeacherForm, TeacherEditForm


class ListTeachersView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ('teachers.view_teacher',)
    model = Teacher
    template_name = 'teacher_list.html'


class AddTeacherView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('teachers.add_teacher',)
    model = Teacher
    form_class = TeacherForm
    template_name = 'teacher_add_edit.html'
    success_url = reverse_lazy('teacher:list')

    def form_valid(self, form):
        """
        Form with extra data, create user and complete basic data, assign to group 'Profesor', save both objects
        """""
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.groups.add(Group.objects.get(name='Profesor'))
        user.save()

        teacher = form.save(commit=False)
        teacher.user = user
        teacher.created_by = self.request.user
        teacher.updated_by = self.request.user
        teacher.save()
        messages.success(self.request, 'Profesor creado con éxito')
        return super(AddTeacherView, self).form_valid(form)


class DetailTeacherView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = ('teachers.view_teacher',)
    model = Teacher
    template_name = 'teacher_detail.html'


class EditTeacherView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('teachers.change_teacher',)
    model = Teacher
    form_class = TeacherEditForm
    template_name = 'teacher_add_edit.html'
    success_url = reverse_lazy('teacher:list')
    data = {}

    def get_context_data(self, **kwargs):
        teacher = Teacher.objects.get(pk=self.kwargs['pk'])
        user = teacher.user
        self.data = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'username': user.username,
            'document_type': teacher.document_type,
            'document_number': teacher.document_number,
            'address': teacher.address,
            'phone': teacher.phone,
            'cellphone': teacher.cellphone
        }
        context = super(EditTeacherView, self).get_context_data(**kwargs)
        context['form'] = self.form_class(initial=self.data)
        return context

    def form_valid(self, form):
        """
        Form with extra data, create user and complete basic data, assign to group 'Profesor', save both objects
        """""
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        user = User.objects.get(username=username)
        user.email = email
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        teacher = form.save(commit=False)
        teacher.user = user
        teacher.updated_by = self.request.user
        teacher.save()
        messages.success(self.request, 'Profesor actualizado con éxito')
        return super(EditTeacherView, self).form_valid(form)

teachers/templates/teacher_add_edit.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        {# TODO: Verificar titulo cuando se edita #}
        {% if request.resolver_match.url_name == 'add' %}
            <h2 class="HeaderModules-title">Agregar profesor</h2>
        {% else %}
            <h2 class="HeaderModules-title">{{ object.get_full_name }}</h2>
        {% endif %}
        <div class="HeaderModules-actions">
            <a href="{% url 'teacher:list' %}" class="Button Button--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="FormModules">
        <form action="." method="post" enctype="multipart/form-data" id="student_form">
            {% csrf_token %}

            <div class="FormModules-row FormModules-row--justify">
                <div class="u-half-width">{{ form.first_name.label_tag }}</div>
                <div class="u-half-width">{{ form.last_name.label_tag }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-half-width">{{ form.first_name }}{{ form.first_name.errors }}</div>
                <div class="u-half-width">{{ form.last_name }}{{ form.last_name.errors }}</div>
            </div>

            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.username.label_tag }}</div>
                <div class="u-quarter-width">{{ form.password.label_tag }}</div>
                <div class="u-half-width">{{ form.email.label_tag }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.username }}{{ form.username.errors }}</div>
                <div class="u-quarter-width">{{ form.password }}{{ form.password.errors }}</div>
                <div class="u-half-width">{{ form.email }}{{ form.email.errors }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.document_type.label_tag }}</div>
                <div class="u-quarter-width">{{ form.document_number.label_tag }}</div>
                <div class="u-half-width">&nbsp;</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.document_type }}{{ form.document_type.errors }}</div>
                <div class="u-quarter-width">{{ form.document_number }}{{ form.document_number.errors }}</div>
                <div class="u-half-width">&nbsp;</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-half-width">{{ form.address.label_tag }}</div>
                <div class="u-quarter-width">{{ form.phone.label_tag }}</div>
                <div class="u-quarter-width">{{ form.cellphone.label_tag }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-half-width">{{ form.address }}{{ form.address.errors }}</div>
                <div class="u-quarter-width">{{ form.phone }}{{ form.phone.errors }}</div>
                <div class="u-quarter-width">{{ form.cellphone }}{{ form.cellphone.errors }}</div>
            </div>
            <div class="FormModules-row FormModules-row--right">
                <button class="Button Button--default" type="submit"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}

teachers/templates/teacher_detail.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">{{ object.get_full_name }}</h2>
        <div class="HeaderModules-actions">
            <a href="{% url 'teacher:list' %}" class="Button Button--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="FormModules">
        <div class="FormModules-row FormModules-row--justify FormModules-row--top">
            <div class="u-half-width">
                <h3>Datos básicos</h3>
                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">Nombres y Apellidos</div>
                    <div class="u-half-width">{{ object.get_full_name }}</div>
                </div>
                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">usuario</div>
                    <div class="u-half-width">{{ object.user.username }}</div>
                </div>

                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">correo electrónico</div>
                    <div class="u-half-width">{{ object.user.email }}</div>
                </div>

                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">Tipo y número de documento</div>
                    <div class="u-half-width">{{ object.get_document_type_display }} {{ object.document_number }}</div>
                </div>

                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">Dirección</div>
                    <div class="u-half-width">{{ object.address }}</div>
                </div>

                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">Teléfono</div>
                    <div class="u-half-width">{{ object.phone }}</div>
                </div>

                <div class="FormModules-row FormModules-row--justify">
                    <div class="u-half-width u-textaling-right">Celular</div>
                    <div class="u-half-width">{{ object.cellphone }}</div>
                </div>
            </div>
            <div class="u-half-width">
                <h3>Materias</h3>
                {% for m in object.syllabus_set.all %}
                    <div class="FormModules-row FormModules-row--justify">
                        <div class="u-full-width">{{ m.matter.name_matter }}</div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

teachers/templates/teacher_list.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de profesores</h2>
        <div class="HeaderModules-actions">
            {% if perms.teachers.add_teacher %}
                <a href="{% url 'teacher:add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Incluir Profesor</a>
            {% endif %}
        </div>
    </div>
    <section class="ListItems-module">
        <table>
            <thead>
                <tr>
                    <th>Nombre completo</th>
                    <th>Identificación</th>
                    <th>Celular</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for s in object_list %}
                    <tr>
                        <td><a href="{% url 'teacher:detail' s.id %}">{{ s.user.get_full_name }}</a></td>
                        <td>{{ s.document_number }}</td>
                        <td>{{ s.cellphone }}</td>
                        <td><a class="Button Button--warning" href="{% url 'teacher:edit' s.id %}"><i class="fa fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}