academico/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from home import urls as home_urls
from student import urls as student_urls
from teachers import urls as teachers_urls
from syllabus import urls as syllabus_urls
from enrollment import urls as enrollment_urls
from ratings import urls as ratings_urls
from attendance import urls as attendance_urls

urlpatterns = [
    url(r'^', include(home_urls, namespace='home')),
    url(r'^estudiantes/', include(student_urls, namespace='student')),
    url(r'^profesores/', include(teachers_urls, namespace='teacher')),
    url(r'^pensum/', include(syllabus_urls, namespace='syllabus')),
    url(r'^matriculas/', include(enrollment_urls, namespace='enrollment')),
    url(r'^calificaciones/', include(ratings_urls, namespace='ratings')),
    url(r'^asistencia/', include(attendance_urls, namespace='attendance')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from .views import HomeView, LogoutView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

student/urls.py
from django.conf.urls import url

from .views import (ListStudentsView, AddStudentView, DetailStudentView,
                    EditStudentView, PrintCertificationIntensity,
                    PrintCertificationQualificationView, PrintDiplomaView)

urlpatterns = [
    url(r'^$', ListStudentsView.as_view(), name='list'),
    url(r'^agregar/$', AddStudentView.as_view(), name='add'),
    url(r'^detalle/(?P<pk>\d+)/$', DetailStudentView.as_view(), name='detail'),
    url(r'^editar/(?P<pk>\d+)/$', EditStudentView.as_view(), name='edit'),
    url(r'^print_intensity/(?P<pk>\d+)/$',
        PrintCertificationIntensity.as_view(), name='print_intensity'),
    url(r'^print_qualification/(?P<pk>\d+)/$',
        PrintCertificationQualificationView.as_view(),
        name='print_qualification'),
    url(r'^print_diploma/(?P<pk>\d+)/$',
        PrintDiplomaView.as_view(),
        name='print_diploma'),
]

student/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from helpers import dictionaries
from home.models import TimeStampUser, Department, Town
from syllabus.models import Syllabus


def photo_folder(self, file):
    ext = file.split('.')[-1]
    filename = '{}_{}.{}'.format(self.first_name, self.last_name, ext)
    return '{}/{}'.format('photos', filename)


class Student(TimeStampUser):
    first_name = models.CharField(
        verbose_name='Nombres',
        max_length=100
    )
    last_name = models.CharField(
        verbose_name='Apellidos',
        max_length=100
    )
    document_type = models.CharField(
        verbose_name='Tipo de documento',
        max_length=2,
        choices=dictionaries.DOCUMENT_TYPE,
        default='CC'
    )
    document_number = models.BigIntegerField(
        verbose_name='Número de documento'
    )
    document_expedition = models.CharField(
        verbose_name='Lugar de expedición',
        max_length=50
    )
    birth_date = models.DateField(
        verbose_name='Fecha de nacimiento'
    )
    birth_department = models.CharField(
        verbose_name='Departamento de nacimiento',
        max_length=50,
        blank=True
    )
    birth_town = models.CharField(
        verbose_name='Ciudad/Municipio de nacimiento',
        max_length=50,
        blank=True
    )
    nationality = models.CharField(
        verbose_name='Nacionalidad',
        max_length=50
    )
    gender = models.CharField(
        verbose_name='Género',
        max_length=1,
        choices=dictionaries.GENDER
    )
    email = models.EmailField(
        verbose_name='Correo eletrónico'
    )
    home_address = models.CharField(
        verbose_name='Dirección de residencia',
        max_length=250
    )
    home_neighborhood = models.CharField(
        verbose_name='Barrio de residencia',
        max_length=50
    )
    home_department = models.ForeignKey(
        Department,
        verbose_name='Departamento de residencia'
    )
    home_town = models.ForeignKey(
        Town,
        verbose_name='Municipio de residencia'
    )
    phone = models.BigIntegerField(
        verbose_name='Teléfono fijo'
    )
    cellphone = models.BigIntegerField(
        verbose_name='Teléfono movil'
    )

    stratum = models.SmallIntegerField(
        verbose_name='Estrato',
        validators=[
            MaxValueValidator(6),
            MinValueValidator(1)
        ]
    )
    civil_state = models.CharField(
        verbose_name='Estado civil',
        max_length=2,
        choices=dictionaries.CIVIL_STATE,
        default='SO'
    )
    has_sisben = models.BooleanField(
        verbose_name='¿Tiene sisben?',
        default=False
    )
    level_sisben = models.DecimalField(
        verbose_name='Nivel sisben',
        decimal_places=2,
        max_digits=8,
        blank=True,
        null=True
    )
    ethnic = models.CharField(
        verbose_name='Grupo etnico',
        max_length=2,
        choices=dictionaries.ETHNIC,
        default='No'
    )
    disability_type = models.CharField(
        verbose_name='Tipo de discapacidad',
        max_length=2,
        choices=dictionaries.DISABILITY_TYPE,
        default='N'
    )
    blood_type = models.CharField(
        verbose_name='Tipo de sangre',
        max_length=2,
        choices=dictionaries.BLOOD_TYPE,
        default='O+'
    )
    education_level = models.CharField(
        verbose_name='Grado de escolaridad',
        max_length=20,
        choices=dictionaries.EDUCATION_LEVEL,
        default='secundaria'
    )
    photo = models.ImageField(
        verbose_name='Foto',
        upload_to=photo_folder
    )
    contact_first_name = models.CharField(
        verbose_name='Nombres',
        max_length=100
    )
    contact_last_name = models.CharField(
        verbose_name='Apellidos',
        max_length=100,
    )
    contact_address = models.CharField(
        verbose_name='Dirección',
        max_length=250
    )
    contact_phone = models.BigIntegerField(
        verbose_name='Teléfono'
    )
    contact_type = models.CharField(
        verbose_name='Parentesco',
        max_length=1,
        choices=dictionaries.CONTACT_TYPE,
        default='1'
    )
    state = models.CharField(
        verbose_name='Estado',
        max_length=2,
        choices=dictionaries.STUDENT_STATE,
        default='a'
    )

    class Meta:
        verbose_name = 'Estudiante'
        verbose_name_plural = 'Estudiantes'
        ordering = ['last_name', 'first_name']
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

    def get_full_name_student(self):
        return '{} {}'.format(self.last_name, self.first_name)


# class Qualification(TimeStampUser):
#     student = models.ForeignKey(
#         Student,
#         verbose_name='Estudiante'
#     )
#     matter = models.ForeignKey(
#         Syllabus
#     )
#     qualification = models.DecimalField(
#         verbose_name='Calificación',
#         decimal_places=1,
#         max_digits=2
#     )
#
#     class Meta:
#         verbose_name = 'Calificación'
#         verbose_name_plural = 'Calificaciones'
#         default_permissions = ('add', 'change', 'delete', 'view',)
#
#     def __str__(self):
#         return '{} - {} - {}'.format(self.student.get_full_name_student(), self.matter, self.qualification)
#
#
# class Assistance(TimeStampUser):
#     student = models.ForeignKey(
#         Student,
#         verbose_name='Estudiante'
#     )
#     matter = models.ForeignKey(
#         Syllabus
#     )
#     assistance = models.SmallIntegerField(
#         verbose_name='Asistencia'
#     )
#
#     def __str__(self):
#         return '{} - {} - {}'.format(self.student.get_full_name_student(), self.matter, self.assistance)

student/forms.py
from django import forms
from django.utils.encoding import force_text
from django.utils.html import escape, conditional_escape

from home.models import Town
from syllabus.models import AcademicOffer
from .models import Student


class SelectWithData(forms.Select):
    def render_option(self, selected_choices, option_value, option_label):
        obj_data = {
            obj.cod_town: {
                data_attr: getattr(obj, data_attr) for data_attr in self.data_attrs
            } for obj in self.queryset
        }

        data_text = ''
        for data_attr in self.data_attrs:
            data_text += ' data-{}="{}" '.format(
                data_attr,
                escape(force_text('')) if option_value == '' else escape(force_text(obj_data[option_value][data_attr].cod))
            )

        option_value = force_text(option_value)
        selected_html = (option_value in selected_choices) and ' selected="selected"' or ''
        return '<option value="{}"{}{}>{}</option>'.format(
            escape(option_value),
            data_text,
            selected_html,
            conditional_escape(force_text(option_label))
        )


class ModelChoiceFieldWithData(forms.ModelChoiceField):
    widget = SelectWithData

    def __init__(self, queryset, **kwargs):
        data_attrs = kwargs.pop('data_attrs')
        super(ModelChoiceFieldWithData, self).__init__(queryset, **kwargs)
        self.widget.queryset = queryset
        self.widget.data_attrs = data_attrs


class StudentForm(forms.ModelForm):
    home_town = ModelChoiceFieldWithData(
        queryset=Town.objects.all(),
        data_attrs=('department',),
        label='Municipio de residencia'
    )
    program = forms.ChoiceField(
        label='Programa al que se matricula',
    )

    class Meta:
        model = Student
        exclude = ('created_by', 'updated_by',)
        widgets = {
            'has_sisben': forms.Select(choices=(('True', 'Sí'), ('False', 'No'),)),
            'document_number': forms.TextInput(),
            'phone': forms.TextInput(),
            'cellphone': forms.TextInput(),
            'contact_phone': forms.TextInput(),
            'level_sisben': forms.TextInput(),
            'stratum': forms.TextInput()
        }

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        academicOffer = AcademicOffer.objects.filter(is_current=True).values_list(
            'id', 'program__name_program', 'day_trip', 'year'
        )
        academic_offer = []
        for a in academicOffer:
            academic_offer.append((str(a[0]), a[1]+' - '+a[2]+' - '+str(a[3])))
        self.fields['program'].choices = list(academic_offer)

student/views.py
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import (ListView, CreateView, DetailView, UpdateView,
                                  View)

from syllabus.models import AcademicOffer
from .models import Student
from .forms import StudentForm
from .utils import (certification_intensity, certification_qualification,
                    diploma)
from enrollment.models import Enrollment


class ListStudentsView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Student
    template_name = 'student_list.html'
    permission_required = ('student.view_student',)

    def get_queryset(self):
        queryset = self.model.objects.exclude(state='r')
        return queryset


class AddStudentView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('student.add_student',)
    model = Student
    form_class = StudentForm
    template_name = 'student_add_edit.html'
    success_url = reverse_lazy('student:list')

    def form_valid(self, form):
        student = form.save(commit=False)
        student.created_by = self.request.user
        student.updated_by = self.request.user
        student.save()
        program = form.cleaned_data['program']
        a = AcademicOffer.objects.get(pk=program)
        p = Enrollment(program=a, student=student)
        p.created_by = self.request.user
        p.updated_by = self.request.user
        p.save()
        messages.success(self.request, 'Estudiante creado con éxito')
        return super(AddStudentView, self).form_valid(form)


class DetailStudentView(LoginRequiredMixin, PermissionRequiredMixin,
                        DetailView):
    permission_required = ('student.view_student',)
    model = Student
    template_name = 'student_detail.html'


class EditStudentView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('student.change_student',)
    model = Student
    form_class = StudentForm
    template_name = 'student_add_edit.html'
    success_url = reverse_lazy('student:list')

    def form_valid(self, form):
        student = form.save(commit=False)
        student.updated_by = self.request.user
        student.save()
        program = form.cleaned_data['program']
        a = AcademicOffer.objects.get(pk=program)
        try:
            p = Enrollment.objects.get(student=student)
            p.program = a
        except:
            p = Enrollment(program=a, student=student)
            p.created_by = self.request.user
        p.updated_by = self.request.user
        p.save()
        messages.success(self.request, 'Estudiante actualizado con éxito')
        return super(EditStudentView, self).form_valid(form)


class PrintCertificationIntensity(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            student = Student.objects.get(pk=self.kwargs['pk'])
            return certification_intensity(student)
        return HttpResponseRedirect('/')


class PrintCertificationQualificationView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            student = Student.objects.get(pk=self.kwargs['pk'])
            return certification_qualification(student)
        return HttpResponseRedirect('/')


class PrintDiplomaView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            student = Student.objects.get(pk=self.kwargs['pk'])
            return diploma(student)
        return HttpResponseRedirect('/')

student/templates/student_detail.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        {# TODO: Verificar titulo cuando se edita #}
        <h2 class="HeaderModules-title">{{ object.get_full_name_student }}</h2>
        <div class="HeaderModules-actions">
            <a href="{% url 'student:print_intensity' object.id %}" class="Button Button--default"><i class="fa fa-file-text"> Certificación</i></a>
            <a href="{% url 'student:print_qualification' object.id %}" class="Button Button--default"><i class="fa fa-file-text-o"> Sabana Notas</i></a>
            <a href="{% url 'student:print_diploma' object.id %}" class="Button Button--default"><i class="fa fa-graduation-cap"> Diploma</i></a>
            <a href="{% url 'student:edit' object.id %}" class="Button Button--default"><i class="fa fa-edit"> Editar</i></a>
            <a href="{% url 'student:list' %}" class="Button Button--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="Detail u-position--relative">
        <div class="Photo-student"><img src="{{ MEDIA_URL }}{{ object.photo }}" alt=""></div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width u-bold">Nombres</div>
            <div class="u-half-width u-bold">Apellidos</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width">{{ object.first_name }}</div>
            <div class="u-half-width">{{ object.last_name }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width u-bold">Tipo documento</div>
            <div class="u-third-width u-bold">Número de documento</div>
            <div class="u-third-width u-bold">Lugar de expedición</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width">{{ object.document_type }}</div>
            <div class="u-third-width">{{ object.document_number }}</div>
            <div class="u-third-width">{{ object.document_expedition }}</div>
        </div>

        <div class="Detail-row Detail-row--left">
            <div class="u-quarter-width u-bold">
                Fecha de nacimiento
            </div>
        </div>
        <div class="Detail-row Detail-row--left">
            <div class="u-quarter-width">
                {{ object.birth_date }}
            </div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width u-bold">Departamento de Nacimiento</div>
            <div class="u-third-width u-bold">Ciudad/Municipio de Nacimiento</div>
            <div class="u-third-width u-bold">Nacionalidad</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width">{{ object.birth_department }}</div>
            <div class="u-third-width">{{ object.birth_town }}</div>
            <div class="u-third-width">{{ object.nationality }}</div>
        </div>

        <div class="Detail-row Detail-row--left">
            <div class="u-quarter-width u-bold">
                Sexo
            </div>
        </div>
        <div class="Detail-row Detail-row--left">
            <div class="u-quarter-width">
                {{ object.get_gender_display }}
            </div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width u-bold">Departamento de residencia</div>
            <div class="u-third-width u-bold">Ciudad/Municipio de residencia</div>
            <div class="u-third-width u-bold">Barrio de residencia</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-third-width">{{ object.home_department }}</div>
            <div class="u-third-width">{{ object.home_town }}</div>
            <div class="u-third-width">{{ object.home_neighborhood }}</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-full-width u-bold">Dirección de residencia</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-full-width">{{ object.home_address }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width u-bold">Correo electrónico</div>
            <div class="u-quarter-width u-bold">Teléfono</div>
            <div class="u-quarter-width u-bold">Celular</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width">{{ object.email }}</div>
            <div class="u-quarter-width">{{ object.phone }}</div>
            <div class="u-quarter-width">{{ object.cellphone }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-quarter-width u-bold">Estrato</div>
            <div class="u-quarter-width u-bold">Estado civil</div>
            <div class="u-quarter-width u-bold">Tiene sisben</div>
            <div class="u-quarter-width u-bold">Nivel de sisben</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-quarter-width">{{ object.stratum }}</div>
            <div class="u-quarter-width">{{ object.get_civil_state_display }}</div>
            <div class="u-quarter-width">{{ object.has_sisben|yesno:'Si, No' }}</div>
            <div class="u-quarter-width">{{ object.level_sisben }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-quarter-width u-bold">Grupo Étnico</div>
            <div class="u-quarter-width u-bold">Tipo de discapacidad</div>
            <div class="u-quarter-width u-bold">Tipo de sangre</div>
            <div class="u-quarter-width u-bold">Grado de escolaridad</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-quarter-width">{{ object.get_ethnic_display }}</div>
            <div class="u-quarter-width">{{ object.get_disability_type_display }}</div>
            <div class="u-quarter-width">{{ object.get_blood_type_display }}</div>
            <div class="u-quarter-width">{{ object.get_education_level_display }}</div>
        </div>
        <div class="Detail-row Detail-row--left">
{#                <div class="u-half-width u-bold">Foto</div>#}
            <div class="u-half-width u-bold">Estado</div>
        </div>
        <div class="Detail-row Detail-row--left">
{#                <div class="u-half-width"><img src="{{ MEDIA_URL }}{{ object.photo }}" alt="" width="216"></div>#}
                <div class="u-half-width">{{ object.get_state_display }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <h3>Datos persona de contacto</h3>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width u-bold">Nombres</div>
            <div class="u-half-width u-bold">Apellidos</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width">{{ object.contact_first_name }}</div>
            <div class="u-half-width">{{ object.contact_last_name }}</div>
        </div>

        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width u-bold">Dirección</div>
            <div class="u-quarter-width u-bold">Teléfono</div>
            <div class="u-quarter-width u-bold">Parentesco</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <div class="u-half-width">{{ object.contact_address }}</div>
            <div class="u-quarter-width">{{ object.contact_phone }}</div>
            <div class="u-quarter-width">{{ object.get_contact_type_display }}</div>
        </div>
        <div class="Detail-row Detail-row--justify">
            <h3>Programa Inscrito</h3>
        </div>
        {% for e in object.enrollment_set.all %}
            <div class="Detail-row Detail-row--left">
                <div class="u-quarter-width">{{ e.program }}</div>
            </div>
        {% endfor %}
        <div class="Detail-row Detail-row--justify">
            <h3>Calificaciones</h3>
        </div>
        {% for e in object.ratenotes_set.all %}
            {% if forloop.first %}
                <div class="Detail-row Detail-row--justify">
                    <div class="u-half-width">Materia</div>
                    <div class="u-half-width">Calificación</div>
                </div>
            {% endif %}
            <div class="Detail-row Detail-row--justify">
                <div class="u-half-width">{{ e.matter.matter.name_matter }}</div>
                <div class="u-half-width">{{ e.qualification }}</div>
            </div>
        {% endfor %}

        <div class="Detail-row Detail-row--justify">
            <h3>Asistencia</h3>
        </div>
        {% for e in object.attendance_set.all %}
            {% if forloop.first %}
                <div class="Detail-row Detail-row--justify">
                    <div class="u-half-width">Materia</div>
                    <div class="u-half-width">Asistencia</div>
                </div>
            {% endif %}
            <div class="Detail-row Detail-row--justify">
                <div class="u-half-width">{{ e.matter.matter.name_matter }}</div>
                <div class="u-half-width">{{ e.attendance }}</div>
            </div>
        {% endfor %}

    </section>
{% endblock %}

student/templates/student_list.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de estudiantes</h2>
        <div class="HeaderModules-actions">
            {% if perms.student.add_student %}
                <a href="{% url 'student:add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Agregar Estudiante</a>
            {% endif %}
        </div>
    </div>
    <section class="ListItems-module">
        <table>
            <thead>
                <tr>
                    <th>Nombre completo</th>
                    <th>Identificación</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for s in object_list %}
                    <tr>
                        {% if perms.student.view_student %}
                            <td><a href="{% url 'student:detail' s.id %}">{{ s.get_full_name_student }}</a></td>
                        {% else %}
                            <td>{{ s.get_full_name_student }}</td>
                        {% endif %}
                        <td>{{ s.document_number }}</td>
                        <td><a href="{% url 'student:edit' s.id %}" class="Button Button--default"><i class="fa fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}