academico/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from home import urls as home_urls
from student import urls as student_urls
from teachers import urls as teachers_urls
from syllabus import urls as syllabus_urls
from enrollment import urls as enrollment_urls
from ratings import urls as ratings_urls
from attendance import urls as attendance_urls

urlpatterns = [
    url(r'^', include(home_urls, namespace='home')),
    url(r'^estudiantes/', include(student_urls, namespace='student')),
    url(r'^profesores/', include(teachers_urls, namespace='teacher')),
    url(r'^pensum/', include(syllabus_urls, namespace='syllabus')),
    url(r'^matriculas/', include(enrollment_urls, namespace='enrollment')),
    url(r'^calificaciones/', include(ratings_urls, namespace='ratings')),
    url(r'^asistencia/', include(attendance_urls, namespace='attendance')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from .views import HomeView, LogoutView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

syllabus/urls.py
from django.conf.urls import url

from .views import (ProgramListView, ProgramCreateView, ProgramEditView,
                    MatterListView, MatterCreateView, MatterEditView,
                    AcademicOfferListView, AcademicOfferCreateView,
                    AcademicOfferEditView, SyllabusView, SyllabusAjaxView,
                    SyllabusDeleteView, SyllabusEditView)

urlpatterns = [
    url(r'^curso/$', ProgramListView.as_view(), name='program_home'),
    url(r'^curso/agregar/$', ProgramCreateView.as_view(), name='program_add'),
    url(r'^curso/editar/(?P<pk>\d+)/$', ProgramEditView.as_view(),
        name='program_edit'),
    url(r'^materia/$', MatterListView.as_view(), name='matter_home'),
    url(r'^materia/agregar/$', MatterCreateView.as_view(), name='matter_add'),
    url(r'^materia/editar/(?P<pk>\d+)/$', MatterEditView.as_view(),
        name='matter_edit'),
    url(r'^periodo/$', AcademicOfferListView.as_view(),
        name='academic_offer_home'),
    url(r'^periodo/agregar/$', AcademicOfferCreateView.as_view(),
        name='academic_offer_add'),
    url(r'^periodo/editar/(?P<pk>\d+)/$', AcademicOfferEditView.as_view(),
        name='academic_offer_edit'),
    url(r'^programa/(?P<pgr>\d+)/$', SyllabusView.as_view(),
        name='syllabus_add'),
url(r'^programa/(?P<pgr>\d+)/edit/(?P<pk>\d+)/$', SyllabusEditView.as_view(),
        name='syllabus_edit'),
    url(r'^programa/(?P<pgr>\d+)/borrar-materia/(?P<pk>\d+)/$',
        SyllabusDeleteView.as_view(), name='syllabus_delete'),
    url(r'^programa/get/(?P<pgr>\d+)/$', SyllabusAjaxView.as_view(),
        name='syllabus_get_ajax')
]

syllabus/models.py
from datetime import date
from django.db import models

from helpers import dictionaries
from home.models import TimeStampUser
from teachers.models import Teacher

from multiselectfield import MultiSelectField


class Program(TimeStampUser):
    """
    Model with programs inherit from TimeStampUser Abstract Class
    """
    name_program = models.CharField(
        verbose_name='Nombre del programa',
        max_length=80
    )

    class Meta:
        verbose_name = 'Programa'
        verbose_name_plural = 'Programas'
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{}'.format(self.name_program)


class Matter(TimeStampUser):
    """
    Model with matters and code inherit from TimeStampUser Abstract Class
    """
    name_matter = models.CharField(
        verbose_name='Nombre de la materia',
        max_length=50
    )
    cod_matter = models.CharField(
        verbose_name='Código de la materia',
        max_length=10
    )

    class Meta:
        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{}'.format(self.name_matter)


class AcademicOffer(TimeStampUser):
    """
    Model with academic offer inherit from TimeStampUser Abstract Class
    """
    program = models.ForeignKey(
        Program,
        verbose_name='Programa'
    )
    year = models.SmallIntegerField(
        verbose_name='Año'
    )
    day_trip = models.CharField(
        verbose_name='Jornada',
        max_length=1,
        choices=dictionaries.DAY_TRIP
    )
    is_current = models.BooleanField(
        verbose_name='Programa activo',
        default=True
    )
    total_hours = models.IntegerField(
        verbose_name='Horas totales del programa',
        default=0
    )
    week_hours = models.IntegerField(
        verbose_name='Horas a la semana',
        default=0
    )

    class Meta:
        verbose_name = 'Oferta acádemica'
        verbose_name_plural = 'Oferta acádemica'
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{} - {} - {}'.format(self.program.name_program, self.year,
                                     self.get_day_trip_display())

    def get_description(self):
        return '{} - {} - {}'.format(self.program.name_program, self.year,
                                     self.get_day_trip_display())


class Syllabus(TimeStampUser):
    """
    Model with syllabus inherit from TimeStampUser Abstract Class
    """
    syllabus = models.ForeignKey(
        AcademicOffer,
        verbose_name='Programa'
    )
    matter = models.ForeignKey(
        Matter,
        verbose_name='Materia'
    )
    hours = models.SmallIntegerField(
        verbose_name='# de horas resolución'
    )
    hours_week = models.SmallIntegerField(
        verbose_name='# de horas semana'
    )
    date_init = models.DateField(
        verbose_name='Inicia'
    )
    date_end = models.DateField(
        verbose_name='Termina'
    )
    day_week = MultiSelectField(
        verbose_name='Día',
        choices=dictionaries.DAYS_OF_WEEK
    )
    schedule = models.CharField(
        verbose_name='Hora',
        max_length=5
    )
    teacher = models.ForeignKey(
        Teacher,
        verbose_name='Profesor'
    )
    limit_report = models.DateField(
        verbose_name='Fecha limite reporte de información'
    )

    class Meta:
        verbose_name = 'Pensum'
        verbose_name_plural = 'Pensum'
        default_permissions = ('add', 'change', 'delete', 'view',)
        ordering = ('id', )

    def __str__(self):
        return '{} - {} - {}'.format(self.syllabus.program.name_program,
                                     self.matter.name_matter,
                                     self.teacher.get_full_name())

    @property
    def is_past_due(self):
        if date.today() > self.limit_report:
            return True
        return False

syllabus/forms.py
from django import forms

from .models import Program, Matter, AcademicOffer, Syllabus


class ProgramForm(forms.ModelForm):

    class Meta:
        model = Program
        exclude = ('created_by', 'updated_by',)


class MatterForm(forms.ModelForm):

    class Meta:
        model = Matter
        exclude = ('created_by', 'updated_by',)


class AcademicOfferForm(forms.ModelForm):

    class Meta:
        model = AcademicOffer
        exclude = ('created_by', 'updated_by',)
        widgets = {
            'year': forms.TextInput()
        }


class SyllabusForm(forms.ModelForm):

    class Meta:
        model = Syllabus
        exclude = ('created_by', 'updated_by', 'syllabus')

syllabus/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.views.generic import DetailView
from django.views.generic import (ListView, CreateView, UpdateView, DeleteView,
                                  View)

from .forms import ProgramForm, MatterForm, AcademicOfferForm, SyllabusForm
from .models import Program, Matter, AcademicOffer, Syllabus


class ProgramListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Program
    permission_required = ('syllabus.view_program',)
    template_name = 'program_home.html'


class ProgramCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Program
    form_class = ProgramForm
    success_url = reverse_lazy('syllabus:program_home')
    template_name = 'program_add_edit.html'
    permission_required = ('syllabus.add_program',)

    def form_valid(self, form):
        program = form.save(commit=False)
        program.created_by = self.request.user
        program.updated_by = self.request.user
        program.save()
        messages.success(self.request, 'Programa creado con exito')
        return super(ProgramCreateView, self).form_valid(form)


class ProgramEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Program
    form_class = ProgramForm
    success_url = reverse_lazy('syllabus:program_home')
    template_name = 'program_add_edit.html'
    permission_required = ('syllabus.change_program',)

    def form_valid(self, form):
        program = form.save(commit=False)
        program.updated_by = self.request.user
        program.save()
        messages.success(self.request, 'Programa actualizado con exito')
        return super(ProgramEditView, self).form_valid(form)


class MatterListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Matter
    permission_required = ('syllabus.view_matter',)
    template_name = 'matter_home.html'


class MatterCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Matter,
    form_class = MatterForm
    success_url = reverse_lazy('syllabus:matter_home')
    permission_required = ('syllabus.add_matter',)
    template_name = 'matter_add_edit.html'

    def form_valid(self, form):
        matter = form.save(commit=False)
        matter.created_by = self.request.user
        matter.updated_by = self.request.user
        matter.save()
        messages.success(self.request, 'Materia creada con éxito')
        return super(MatterCreateView, self).form_valid(form)


class MatterEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Matter
    form_class = MatterForm
    success_url = reverse_lazy('syllabus:matter_home')
    permission_required = ('syllabus.change_matter',)
    template_name = 'matter_add_edit.html'

    def form_valid(self, form):
        matter = form.save(commit=False)
        matter.updated_by = self.request.user
        matter.save()
        messages.success(self.request, 'Materia actualizada con éxito')
        return super(MatterEditView, self).form_valid(form)


class AcademicOfferListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = AcademicOffer
    permission_required = ('syllabus.view_academicoffer',)
    template_name = 'academic_offer_home.html'


class AcademicOfferCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = AcademicOffer
    form_class = AcademicOfferForm
    success_url = reverse_lazy('syllabus:academic_offer_home')
    permission_required = ('syllabus.add_academicoffer',)
    template_name = 'academic_offer_add_edit.html'

    def form_valid(self, form):
        acadmic_offer = form.save(commit=False)
        acadmic_offer.created_by = self.request.user
        acadmic_offer.updated_by = self.request.user
        acadmic_offer.save()
        messages.success(self.request, 'Periodo academico creado con éxito')
        return super(AcademicOfferCreateView, self).form_valid(form)


class AcademicOfferEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = AcademicOffer
    form_class = AcademicOfferForm
    success_url = reverse_lazy('syllabus:academic_offer_home')
    permission_required = ('syllabus.change_academicoffer',)
    template_name = 'academic_offer_add_edit.html'

    def form_valid(self, form):
        academic_offer = form.save(commit=False)
        academic_offer.updated_by = self.request.user
        academic_offer.save()
        messages.success(self.request, 'Periodo academico actualizado con éxito')
        return super(AcademicOfferEditView, self).form_valid(form)


# class SyllabusListView(LoginRequiredMixin, PermissionsRequiredMixin, ListView):
#     model = Syllabus
#     required_permissions = ('syllabus.syllabus_view',)
#     template_name = 'syllabus_home.html'


# class SyllabusCreateView(LoginRequiredMixin, PermissionsRequiredMixin, CreateView):
#     model = Syllabus
#     form_class = SyllabusForm
#     success_url = reverse_lazy('syllabus:syllabus_home')
#     required_permissions = ('syllabus.syllabus_add',)
#     template_name = 'syllabus_add_edit.html'
#     formset = modelformset_factory(model, exclude=('created_by', 'updated_by', 'syllabus',))
#
#     def get_context_data(self, **kwargs):
#         context = super(SyllabusCreateView, self).get_context_data(**kwargs)
#         if self.request.POST:
#             context['formset'] = self.formset(self.request.POST)
#         else:
#             context['formset'] = self.formset()
#         return context
#
#     def form_valid(self, form):
#         syllabus = form.save(commit=False)
#         syllabus.created_by = self.request.user
#         syllabus.updated_by = self.request.user
#         syllabus.save()
#         messages.success(self.request, 'El pensum ha sido creado con éxito')
#         return super(SyllabusCreateView, self).form_valid(form)


class SyllabusView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Syllabus
    form_class = SyllabusForm
    template_name = 'syllabus_home.html'
    permission_required = ('syllabus.view_syllabus', )

    def form_valid(self, form):
        program = AcademicOffer.objects.get(pk=self.kwargs['pgr'])

        if self.request.is_ajax():
            pensum = form.save(commit=False)
            pensum.created_by = self.request.user
            pensum.updated_by = self.request.user
            pensum.syllabus = program
            pensum.save()
            return JsonResponse({'status': 200})
        else:
            return JsonResponse({'status': 403})
        # super(SyllabusView, self).form_valid(form)

    def form_invalid(self, form):
        return JsonResponse({'status': 500})

    def get_context_data(self, **kwargs):
        program = AcademicOffer.objects.get(pk=self.kwargs['pgr'])
        pensum = Syllabus.objects.filter(syllabus=program.pk)
        context = super(SyllabusView, self).get_context_data(**kwargs)
        context['pensum'] = pensum
        context['program'] = program.id
        return context


class SyllabusEditView(LoginRequiredMixin, PermissionRequiredMixin,
                       UpdateView):
    model = Syllabus
    form_class = SyllabusForm
    template_name = 'syllabus_home.html'
    permission_required = ('syllabus.change_syllabus',)

    def form_valid(self, form):
        program = AcademicOffer.objects.get(pk=self.kwargs['pgr'])

        if self.request.is_ajax():
            pensum = form.save(commit=False)
            pensum.created_by = self.request.user
            pensum.updated_by = self.request.user
            pensum.syllabus = program
            pensum.save()
            return JsonResponse({'status': 200})
        else:
            return JsonResponse({'status': 403})
            # super(SyllabusView, self).form_valid(form)

    def form_invalid(self, form):
        return JsonResponse({'status': 500})


class SyllabusAjaxView(LoginRequiredMixin, PermissionRequiredMixin,
                       DetailView):
    model = Syllabus
    permission_required = ('syllabus.change_syllabus',)
    template_name = ''

    def get(self, request, *args, **kwargs):
        if self.request.is_ajax:
            syllabus = Syllabus.objects.get(id=self.kwargs['pgr'])
            data = {
                'id': syllabus.id,
                'syllabus': syllabus.syllabus_id,
                'matter': syllabus.matter_id,
                'hours': syllabus.hours,
                'hours_week': syllabus.hours_week,
                'date_init': syllabus.date_init,
                'date_end': syllabus.date_end,
                'day_week': syllabus.day_week,
                'schedule': syllabus.schedule,
                'teacher': syllabus.teacher_id,
                'limit_report': syllabus.limit_report,
            }
            return JsonResponse(data=data, status=200)


class SyllabusDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Syllabus
    permission_required = ('syllabus.delete_syllabus',)
    # success_url = reverse_lazy('syllabus:syllabus_add')
    template_name = 'syllabus_delete.html'

    def get_success_url(self):
        return reverse_lazy('syllabus:syllabus_add', kwargs={'pgr': self.kwargs['pgr']})
        # super(SyllabusDeleteView, self).get_success_url(**kwargs)

syllabus/templates/academic_offer_add_edit.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        {# TODO: Verificar titulo cuando se edita #}
        {% if request.resolver_match.url_name == 'add' %}
            <h2 class="HeaderModules-title">Agregar programa</h2>
        {% else %}
            <h2 class="HeaderModules-title">{{ object.get_description }}</h2>
        {% endif %}
        <div class="HeaderModules-actions">
            <a href="{% url 'syllabus:matter_home' %}" class="Button Button--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="FormModules">
        <form action="." method="post">
            {% csrf_token %}

            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.program.label_tag }}</div>
                <div class="u-quarter-width">{{ form.year.label_tag }}</div>
                <div class="u-quarter-width">{{ form.day_trip.label_tag }}</div>
                <div class="u-quarter-width">{{ form.is_current.label_tag }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.program }}{{ form.program.errors }}</div>
                <div class="u-quarter-width">{{ form.year }}{{ form.year.errors }}</div>
                <div class="u-quarter-width">{{ form.day_trip }}{{ form.day_trip.errors }}</div>
                <div class="u-quarter-width">{{ form.is_current }}{{ form.is_current.errors }}</div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.total_hours.label_tag }}</div>
                <div class="u-quarter-width">{{ form.week_hours.label_tag }}</div>
                <div class="u-half-width"></div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">{{ form.total_hours }}{{ form.total_hours.errors }}</div>
                <div class="u-quarter-width">{{ form.week_hours }}{{ form.week_hours.errors }}</div>
                <div class="u-half-width"></div>
            </div>
            <div class="FormModules-row FormModules-row--justify">
                <div class="u-quarter-width">&nbsp;</div>
                <div class="u-half-width">
                    &nbsp;
                </div>
                <div class="u-quarter-width u-textaling-right">
                    <button class="Button Button--default" type="submit"><i class="fa fa-save"></i> Guardar</button>
                </div>

            </div>
        </form>
    </section>
{% endblock %}

syllabus/templates/academic_offer_home.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de Programas</h2>
        <div class="HeaderModules-actions">
            {% if perms.syllabus.add_academicoffer %}
                <a href="{% url 'syllabus:academic_offer_add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Crear Programa</a>
            {% endif %}
        </div>
    </div>
    <section class="ListItems-module">
        <table>
            <thead>
                <tr>
                    <th>Curso</th>
                    <th>Año</th>
                    <th>Jornada</th>
                    <th>Activo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for s in object_list %}
                    <tr>
                        <td>{{ s.program.name_program }}</td>
                        <td>{{ s.year }}</td>
                        <td>{{ s.get_day_trip_display }}</td>
                        <td>{{ s.is_current|yesno:'Activo, Inactivo' }}</td>
                        <td><a class="Button Button--warning" href="{% url 'syllabus:academic_offer_edit' s.id %}"><i class="fa fa-edit"></i></a></td>
                        <td>
                            {% if s.is_current %}
                                <a class="Button Button--warning" href="{% url 'syllabus:syllabus_add' s.id %}"><i class="fa fa-map"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

syllabus/templates/matter_home.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de Materias</h2>
        <div class="HeaderModules-actions">
            {% if perms.syllabus.add_matter %}
                <a href="{% url 'syllabus:matter_add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Crear materia</a>
            {% endif %}
        </div>
    </div>
    <section class="ListItems-module">
        <table>
            <thead>
                <tr>
                    <th>Código de la materia</th>
                    <th>Nombre de la materia</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for s in object_list %}
                    <tr>
                        <td>{{ s.cod_matter }}</td>
                        <td>{{ s.name_matter }}</td>
                        <td><a class="Button Button--warning" href="{% url 'syllabus:matter_edit' s.id %}"><i class="fa fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

syllabus/templates/program_home.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de Cursos</h2>
        <div class="HeaderModules-actions">
            {% if perms.syllabus.add_program %}
                <a href="{% url 'syllabus:program_add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Crear curso</a>
            {% endif %}
        </div>
    </div>
    <section class="ListItems-module">
        <table>
            <thead>
                <tr>
                    <th>Nombre del curso</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for s in object_list %}
                    <tr>
                        <td>{{ s.name_program }}</td>
                        <td><a class="Button Button--warning" href="{% url 'syllabus:program_edit' s.id %}"><i class="fa fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

syllabus/templates/syllabus_add_edit.html
{% extends 'base--logged.html' %}
{% block main--loged %}
    {{ form }}
{% endblock %}

syllabus/templates/syllabus_home.html
{% extends 'base--logged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Crear pensum</h2>
        <div class="HeaderModules-actions">
            <a href="{% url 'syllabus:academic_offer_home' %}" class="Button Button--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width">{{ form.matter.label_tag }}</div>
            <div class="u-half-width">{{ form.teacher.label_tag }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width">{{ form.matter }}</div>
            <div class="u-half-width">{{ form.teacher }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width">{{ form.matter.errors }}</div>
            <div class="u-half-width">{{ form.teacher.errors }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-fifth-width">{{ form.hours.label_tag }}</div>
            <div class="u-fifth-width">{{ form.hours_week.label_tag }}</div>
            <div class="u-fifth-width">{{ form.date_init.label_tag }}</div>
            <div class="u-fifth-width">{{ form.date_end.label_tag }}</div>
            <div class="u-fifth-width">{{ form.schedule.label_tag }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-fifth-width">{{ form.hours }}</div>
            <div class="u-fifth-width">{{ form.hours_week }}</div>
            <div class="u-fifth-width">{{ form.date_init }}</div>
            <div class="u-fifth-width">{{ form.date_end }}</div>
            <div class="u-fifth-width">{{ form.schedule }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-fifth-width">{{ form.hours.errors }}</div>
            <div class="u-fifth-width">{{ form.hours_week.errors }}</div>
            <div class="u-fifth-width">{{ form.date_init.errors }}</div>
            <div class="u-fifth-width">{{ form.date_end.errors }}</div>
            <div class="u-fifth-width">{{ form.schedule.errors }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width">{{ form.day_week.label_tag }}</div>
            <div class="u-half-width">{{ form.limit_report.label_tag }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width ">{{ form.day_week }}</div>
            <div class="u-half-width ">{{ form.limit_report }}</div>
        </div>
        <div class="FormModules-row FormModules-row--justify">
            <div class="u-half-width">{{ form.day_week.errors }}</div>
            <div class="u-half-width">{{ form.limit_report.errors }}</div>
        </div>
        <div class="FormModules-row FormModules-row--right">
            <button class="Button Button--warning" name="save" data-id="{{ program }}" type="submit"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
    <hr>
    <h2>Pensum</h2>
    {% for p in pensum %}
        {% if forloop.first %}
            <table>
                <thead>
                    <tr>
                        <th>Materia</th>
                        <th>Día</th>
                        <th>Hora</th>
                        <th>Inicia</th>
                        <th>Termina</th>
                        <th>Horas</th>
                        <th>Profesor</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

        {% endif %}
                    <tr>
                        <td>{{ p.matter.name_matter }}</td>
                        <td>{{ p.get_day_week_display }}</td>
                        <td>{{ p.schedule }}</td>
                        <td>{{ p.date_init|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>{{ p.date_end|date:"SHORT_DATE_FORMAT" }}</td>
                        <td>{{ p.hours }}</td>
                        <td>{{ p.teacher.get_full_name }}</td>
                        <th><a href="" class="Button Button--default syllabus-edit" data-id="{{ p.id }}"><i class="fa fa-edit"></i></a></th>
                        <th>
                            {% if perms.syllabus.delete_syllabus %}
                            <a href="{% url 'syllabus:syllabus_delete' program p.id  %}" class="Button Button--warning"><i class="fa fa-minus-circle"></i></a>
                            {% endif %}
                        </th>
                    </tr>
        {% if forloop.last %}
                </tbody>
            </table>
        {% endif %}
    {% endfor %}

{% endblock %}
{% block JS %}
    {{ block.super }}
    <script src="{% static 'js/csrf_ajax.js' %}"></script>
    <script src="{% static 'js/syllabus.js' %}"></script>
{% endblock %}