academico/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from home import urls as home_urls
from student import urls as student_urls
from teachers import urls as teachers_urls
from syllabus import urls as syllabus_urls
from enrollment import urls as enrollment_urls
from ratings import urls as ratings_urls
from attendance import urls as attendance_urls

urlpatterns = [
    url(r'^', include(home_urls, namespace='home')),
    url(r'^estudiantes/', include(student_urls, namespace='student')),
    url(r'^profesores/', include(teachers_urls, namespace='teacher')),
    url(r'^pensum/', include(syllabus_urls, namespace='syllabus')),
    url(r'^matriculas/', include(enrollment_urls, namespace='enrollment')),
    url(r'^calificaciones/', include(ratings_urls, namespace='ratings')),
    url(r'^asistencia/', include(attendance_urls, namespace='attendance')),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enrollment/urls.py
from django.conf.urls import url

from .views import EnrollmentListView, EnrollmentView, EnrollmentEditView, EnrollmentDeleteView

urlpatterns = [
    url(r'^$', EnrollmentView.as_view(), name='home'),
    url(r'^borrar/(?P<pk>\d+)/$', EnrollmentDeleteView.as_view(), name='delete')
    # url(r'^matricular/$', EnrollmentCreateView.as_view(), name='add'),
    # url(r'^matricula/(?P<pk>\d+)/$', EnrollmentEditView.as_view(), name='edit'),
]

home/urls.py
from django.conf.urls import url

from .views import HomeView, LogoutView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

enrollment/models.py
from django.db import models

from home.models import TimeStampUser
from student.models import Student
from syllabus.models import AcademicOffer


class Enrollment(TimeStampUser):
    """
    Model with enrollment of student into academic offer inherit from TimeStampUser Abstract Class
    this is inscription model.
    """
    program = models.ForeignKey(
        AcademicOffer,
        verbose_name='Oferta academica'
    )
    student = models.ForeignKey(
        Student,
        verbose_name='Estudiante'
    )

    class Meta:
        verbose_name = 'Inscripción'
        verbose_name_plural = 'Inscripciones'
        default_permissions = ('add', 'change', 'delete', 'view',)

    def __str__(self):
        return '{}'.format(self.student.get_full_name_student())

enrollment/forms.py
from django import forms
from .models import Enrollment
from student.models import Student
from syllabus.models import AcademicOffer


class EnrollmentForm(forms.ModelForm):

    class Meta:
        model = Enrollment
        exclude = ('created_by', 'updated_by',)

    def __init__(self, *args, **kwargs):
        """
        Filter active program and students
        """
        super(EnrollmentForm, self).__init__(*args, **kwargs)
        try:
            queryset_academic = AcademicOffer.objects.filter(is_current=True)
        except:
            queryset_academic = None

        try:
            queryset_students = Student.objects.filter(state='a')
        except:
            queryset_students = None
        self.fields['program'].queryset = queryset_academic
        self.fields['student'].queryset = queryset_students

enrollment/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import EnrollmentForm
from .models import Enrollment


class EnrollmentListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Enrollment
    permission_required = ('enrollment.view_enrollment',)
    template_name = 'enrollment_home.html'


class EnrollmentView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Enrollment
    form_class = EnrollmentForm
    permission_required = ('enrollment.add_enrollment',)
    success_url = reverse_lazy('enrollment:home')
    template_name = 'enrollment_home.html'

    def form_valid(self, form):
        enrollment = form.save(commit=False)
        enrollment.created_by = self.request.user
        enrollment.updated_by = self.request.user
        enrollment.save()
        messages.success(self.request, 'Estudiante matriculado con exito')
        return super(EnrollmentView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EnrollmentView, self).get_context_data(**kwargs)
        context['enrollment_list'] = self.model.objects.all()
        return context


class EnrollmentEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Enrollment
    form_class = EnrollmentForm
    permission_required = ('enrollment.change_enrollment',)
    success_url = reverse_lazy('enrollment:home')
    template_name = 'enrollment_home.html'

    def form_valid(self, form):
        enrollment = form.save(commit=False)
        enrollment.created_by = self.request.user
        enrollment.updated_by = self.request.user
        enrollment.save()
        messages.success(self.request, 'Matricula editada con exito')
        return super(EnrollmentEditView, self).form_valid(form)


class EnrollmentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Enrollment
    permission_required = ('enrollment.delete_enrollment',)
    success_url = reverse_lazy('enrollment:home')
    template_name = 'enrollment_delete.html'

enrollment/templates/enrollment_delete.html
{% extends 'base--logged.html' %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de Matriculas</h2>
        <div class="HeaderModules-actions">
{#            {% if perms.enrollment.add_enrollment %}#}
{#                <a href="{% url 'enrollment:add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Matricular</a>#}
{#            {% endif %}#}
        </div>
    </div>
    {% if perms.enrollment.delete_enrollment %}
        <section class="FormInlineEnrollment">
            <form action="." method="post">
                {% csrf_token %}
                <p>Esta seguro que desea eliminar la matricula de {{ object }}</p>
                <div class="FormModules-row FormModules-row--right">
                    <button type="submit" class="Button Button--default"><i class="fa fa-minus-circle"></i> Borrar</button>
                </div>
            </form>
        </section>
    {% endif %}
{% endblock %}

enrollment/templates/enrollment_home.html
{% extends 'base--logged.html' %}
{% block main--loged %}
    <div class="HeaderModules">
        <h2 class="HeaderModules-title">Listado de Matriculas</h2>
        <div class="HeaderModules-actions">
{#            {% if perms.enrollment.add_enrollment %}#}
{#                <a href="{% url 'enrollment:add' %}" class="Button Button--default"><i class="fa fa-plus-circle"></i> Matricular</a>#}
{#            {% endif %}#}
        </div>
    </div>
{#    {% if perms.enrollment.add_enrollment %}#}
{#        <section class="FormInlineEnrollment">#}
{#            <form action="." method="post">#}
{#                {% csrf_token %}#}
{#                <div class="FormModules-row FormModules-row--justify">#}
{#                    <div class="u-half-width">{{ form.program.label_tag }}</div>#}
{#                    <div class="u-half-width">{{ form.student.label_tag }}</div>#}
{#                </div>#}
{#                <div class="FormModules-row FormModules-row--justify">#}
{#                    <div class="u-half-width">{{ form.program }}</div>#}
{#                    <div class="u-half-width">{{ form.student }}</div>#}
{#                </div>#}
{#                <div class="FormModules-row FormModules-row--justify">#}
{#                    <div class="u-half-width">{{ form.program.errors }}</div>#}
{#                    <div class="u-half-width">{{ form.student.errors }}</div>#}
{#                </div>#}
{#                <div class="FormModules-row FormModules-row--right">#}
{#                    <button type="submit" class="Button Button--default"><i class="fa fa-save"></i> Matricular</button>#}
{#                </div>#}
{#            </form>#}
{#        </section>#}
{#    {% endif %}#}
    <section class="ListItems-module">
{#        <h2>Matriculas</h2>#}
        {% for e in enrollment_list %}
            {% if forloop.first %}
                <table>
                    <thead>
                        <tr>
                            <th>Estudiante</th>
                            <th>Programa</th>
{#                            <th></th>#}
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
            {% endif %}
                        <tr>
                            <td>{{ e.student.get_full_name_student }}</td>
                            <td>{{ e.program.program.name_program }} - {{ e.program.get_day_trip_display }} - {{ e.program.year }}</td>
{#                            <td><a href="" class="Button Button--warning"><i class="fa fa-edit"></i></a></td>#}
                            <td>
                                {% if perms.enrollment.delete_enrollment %}
                                    <a href="{% url 'enrollment:delete' e.id %}" class="Button Button--warning"><i class="fa fa-minus-circle"></i></a>
                                {% endif %}
                            </td>
                        </tr>
            {% if forloop.last %}
                    </tbody>
                </table>
            {% endif %}
        {% endfor %}
    </section>
{% endblock %}